// ============================================================
//  main.dart  –  CashZone Pro entry point
//  Initialises Firebase, sets up providers, launches the app.
// ============================================================

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

import 'firebase_options.dart';          // generated by FlutterFire CLI
import 'services/auth_service.dart';
import 'services/coin_service.dart';
import 'services/ad_service.dart';
import 'services/user_service.dart';
import 'screens/splash_screen.dart';
import 'utils/app_theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── Lock to portrait mode ──────────────────────────────
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
  ]);

  // ── Firebase ──────────────────────────────────────────
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // ── Google Mobile Ads (AdMob / Unity adapter) ─────────
  await MobileAds.instance.initialize();

  runApp(const CashZoneApp());
}

class CashZoneApp extends StatelessWidget {
  const CashZoneApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        // AuthService – tracks Firebase Auth state
        ChangeNotifierProvider(create: (_) => AuthService()),

        // CoinService – manages coins, daily limits, transactions
        ChangeNotifierProvider(create: (_) => CoinService()),

        // UserService – user profile, referrals, leaderboard
        ChangeNotifierProvider(create: (_) => UserService()),

        // AdService – controls ad frequency and rewarded ads
        ChangeNotifierProvider(create: (_) => AdService()),
      ],
      child: MaterialApp(
        title: 'CashZone Pro',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.darkTheme,      // Purple-blue neon dark theme
        home: const SplashScreen(),
      ),
    );
  }
}
